### ISSUE TITLE
ADC/ALB cant reach the pod endpoints , ClusterIP network 

### ISSUE THREAD

**Issue by iahmad-khan** [edgeNEXUS/kubernetes-ingress#7]
Use case:

An app running on Kubernetes needs to be exposed outside via ingress resources and external ADC

Steps:

- deploy ingress controller and CRDS on Kubernetes, ingress controller can talk to external ADC/ALB ( ADC running as appliance on VMware ) , done
- ingress controller can talk to ADC via REST, done
- deploy httpbin app and service, done
- create ingress resource for httpbin, done
- ADC is updated by ingress controller with a virtual service and real server backend, done
- ADC can't reach the backend pods/IPs, this needs fixing.

Possible solution:

the Ingress controller should register the Kubernetes node-port service in ADC instead of Pod IPs/endpoints. Pod/IPs are internal to Kubernetes and cant be reached from external ADC

**Comment by ghowett** [comment]
Currently the system will retrieve the POD/IP from the ingress controller. These IP's are not accessible externally. The system should find the associated  POD IPS's Endpoint that is an external IP:port that is contactable externally. IF there is no an external enpoint found  then it should show the internal Pod/IP as it does currently

**Comment by SmartCodeMaker** [comment]
@ghowett @iahmad-khan This is my actual controller service for `edgenexus-ingress` (of type of `LoadBalancer`):

```
# Source: edgenexus-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: edgenexus-ingress
  namespace: edgenexus-ingress
  labels:
    app.kubernetes.io/name: edgenexus-ingress
    helm.sh/chart: edgenexus-ingress-0.10.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: my-release
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.2.132
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app:  edgenexus-ingress
```


Do you think we need to create `NodePort` instead of `LoadBalancer` type?

```
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: edgenexus-ingress
    helm.sh/chart: edgenexus-ingress-0.10.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/component: controller
  name: edgenexus-ingress
  namespace: edgenexus-ingress
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https
  selector:
    app:  edgenexus-ingress
```

If so, then what should ingress controller do to ADC?
